# Generated by Django 4.2.6 on 2023-10-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ativo_inativo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='data_alteracao',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='data_inclusao',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cnpj_cpf_codigo',
            field=models.CharField(max_length=14),
        ),
    ]
