# Generated by Django 4.2.6 on 2023-10-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaslebes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='janelas',
            name='controlpoint',
        ),
    ]
