# Generated by Django 4.2.6 on 2023-11-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaslebes', '0002_remove_janelas_controlpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='xmlfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='xml_files/')),
            ],
        ),
    ]
