# Generated by Django 4.2.6 on 2023-11-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaslebes', '0004_ocorrencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='id_cte',
            new_name='id_ctenfse',
        ),
    ]
